var annotated_dup =
[
    [ "albert", "namespacealbert.html", [
      [ "Action", "classalbert_1_1_action.html", "classalbert_1_1_action" ],
      [ "BackgroundExecutor", "classalbert_1_1_background_executor.html", "classalbert_1_1_background_executor" ],
      [ "Dependency", "classalbert_1_1_dependency.html", "classalbert_1_1_dependency" ],
      [ "Extension", "classalbert_1_1_extension.html", "classalbert_1_1_extension" ],
      [ "ExtensionPlugin", "classalbert_1_1_extension_plugin.html", "classalbert_1_1_extension_plugin" ],
      [ "ExtensionRegistry", "classalbert_1_1_extension_registry.html", "classalbert_1_1_extension_registry" ],
      [ "FallbackHandler", "classalbert_1_1_fallback_handler.html", "classalbert_1_1_fallback_handler" ],
      [ "Frontend", "classalbert_1_1_frontend.html", "classalbert_1_1_frontend" ],
      [ "GlobalQueryHandler", "classalbert_1_1_global_query_handler.html", "classalbert_1_1_global_query_handler" ],
      [ "IndexItem", "classalbert_1_1_index_item.html", "classalbert_1_1_index_item" ],
      [ "IndexQueryHandler", "classalbert_1_1_index_query_handler.html", "classalbert_1_1_index_query_handler" ],
      [ "InputHistory", "classalbert_1_1_input_history.html", "classalbert_1_1_input_history" ],
      [ "Item", "classalbert_1_1_item.html", "classalbert_1_1_item" ],
      [ "Match", "classalbert_1_1_match.html", "classalbert_1_1_match" ],
      [ "MatchConfig", "classalbert_1_1_match_config.html", "classalbert_1_1_match_config" ],
      [ "Matcher", "classalbert_1_1_matcher.html", "classalbert_1_1_matcher" ],
      [ "Notification", "classalbert_1_1_notification.html", "classalbert_1_1_notification" ],
      [ "PluginInstance", "classalbert_1_1_plugin_instance.html", "classalbert_1_1_plugin_instance" ],
      [ "PluginLoader", "classalbert_1_1_plugin_loader.html", "classalbert_1_1_plugin_loader" ],
      [ "PluginMetaData", "classalbert_1_1_plugin_meta_data.html", "classalbert_1_1_plugin_meta_data" ],
      [ "PluginProvider", "classalbert_1_1_plugin_provider.html", "classalbert_1_1_plugin_provider" ],
      [ "Query", "classalbert_1_1_query.html", "classalbert_1_1_query" ],
      [ "RankItem", "classalbert_1_1_rank_item.html", "classalbert_1_1_rank_item" ],
      [ "ResultItem", "classalbert_1_1_result_item.html", "classalbert_1_1_result_item" ],
      [ "StandardItem", "classalbert_1_1_standard_item.html", "classalbert_1_1_standard_item" ],
      [ "StrongDependency", "classalbert_1_1_strong_dependency.html", "classalbert_1_1_strong_dependency" ],
      [ "TelemetryProvider", "classalbert_1_1_telemetry_provider.html", "classalbert_1_1_telemetry_provider" ],
      [ "TriggerQueryHandler", "classalbert_1_1_trigger_query_handler.html", "classalbert_1_1_trigger_query_handler" ],
      [ "WeakDependency", "classalbert_1_1_weak_dependency.html", "classalbert_1_1_weak_dependency" ]
    ] ],
    [ "TimeIt", "struct_time_it.html", "struct_time_it" ]
];