var dir_f0f46089beeebac69d4f0fa43cb2bbb7 =
[
    [ "action.h", "action_8h.html", "action_8h" ],
    [ "backgroundexecutor.h", "backgroundexecutor_8h.html", "backgroundexecutor_8h" ],
    [ "extension.h", "extension_8h.html", "extension_8h" ],
    [ "extensionplugin.h", "extensionplugin_8h.html", "extensionplugin_8h" ],
    [ "extensionregistry.h", "extensionregistry_8h.html", "extensionregistry_8h" ],
    [ "extensionwatcher.h", "extensionwatcher_8h.html", "extensionwatcher_8h" ],
    [ "fallbackhandler.h", "fallbackhandler_8h.html", "fallbackhandler_8h" ],
    [ "frontend.h", "frontend_8h.html", "frontend_8h" ],
    [ "globalqueryhandler.h", "globalqueryhandler_8h.html", "globalqueryhandler_8h" ],
    [ "iconprovider.h", "iconprovider_8h.html", "iconprovider_8h" ],
    [ "indexitem.h", "indexitem_8h.html", "indexitem_8h" ],
    [ "indexqueryhandler.h", "indexqueryhandler_8h.html", "indexqueryhandler_8h" ],
    [ "inputhistory.h", "inputhistory_8h.html", "inputhistory_8h" ],
    [ "item.h", "item_8h.html", "item_8h" ],
    [ "logging.h", "logging_8h.html", "logging_8h" ],
    [ "matchconfig.h", "matchconfig_8h.html", null ],
    [ "matcher.h", "matcher_8h.html", "matcher_8h" ],
    [ "notification.h", "notification_8h.html", "notification_8h" ],
    [ "plugindependency.h", "plugindependency_8h.html", "plugindependency_8h" ],
    [ "plugininstance.h", "plugininstance_8h.html", "plugininstance_8h" ],
    [ "pluginloader.h", "pluginloader_8h.html", "pluginloader_8h" ],
    [ "pluginmetadata.h", "pluginmetadata_8h.html", "pluginmetadata_8h" ],
    [ "pluginprovider.h", "pluginprovider_8h.html", "pluginprovider_8h" ],
    [ "property.h", "property_8h.html", "property_8h" ],
    [ "query.h", "query_8h.html", "query_8h" ],
    [ "rankitem.h", "rankitem_8h.html", "rankitem_8h" ],
    [ "standarditem.h", "standarditem_8h.html", "standarditem_8h" ],
    [ "triggerqueryhandler.h", "triggerqueryhandler_8h.html", "triggerqueryhandler_8h" ],
    [ "util.h", "util_8h.html", "util_8h" ]
];