var namespacealbert =
[
    [ "experimental", "namespacealbert_1_1experimental.html", "namespacealbert_1_1experimental" ],
    [ "util", "namespacealbert_1_1util.html", "namespacealbert_1_1util" ],
    [ "Action", "classalbert_1_1Action.html", "classalbert_1_1Action" ],
    [ "Dependency", "classalbert_1_1Dependency.html", "classalbert_1_1Dependency" ],
    [ "Extension", "classalbert_1_1Extension.html", "classalbert_1_1Extension" ],
    [ "ExtensionPlugin", "classalbert_1_1ExtensionPlugin.html", "classalbert_1_1ExtensionPlugin" ],
    [ "ExtensionRegistry", "classalbert_1_1ExtensionRegistry.html", "classalbert_1_1ExtensionRegistry" ],
    [ "FallbackHandler", "classalbert_1_1FallbackHandler.html", "classalbert_1_1FallbackHandler" ],
    [ "Frontend", "classalbert_1_1Frontend.html", "classalbert_1_1Frontend" ],
    [ "GlobalQueryHandler", "classalbert_1_1GlobalQueryHandler.html", "classalbert_1_1GlobalQueryHandler" ],
    [ "Item", "classalbert_1_1Item.html", "classalbert_1_1Item" ],
    [ "PluginInstance", "classalbert_1_1PluginInstance.html", "classalbert_1_1PluginInstance" ],
    [ "PluginLoader", "classalbert_1_1PluginLoader.html", "classalbert_1_1PluginLoader" ],
    [ "PluginMetaData", "classalbert_1_1PluginMetaData.html", "classalbert_1_1PluginMetaData" ],
    [ "PluginProvider", "classalbert_1_1PluginProvider.html", "classalbert_1_1PluginProvider" ],
    [ "Query", "classalbert_1_1Query.html", "classalbert_1_1Query" ],
    [ "RankItem", "classalbert_1_1RankItem.html", "classalbert_1_1RankItem" ],
    [ "ResultItem", "classalbert_1_1ResultItem.html", "classalbert_1_1ResultItem" ],
    [ "StrongDependency", "classalbert_1_1StrongDependency.html", "classalbert_1_1StrongDependency" ],
    [ "TelemetryProvider", "classalbert_1_1TelemetryProvider.html", "classalbert_1_1TelemetryProvider" ],
    [ "TriggerQueryHandler", "classalbert_1_1TriggerQueryHandler.html", "classalbert_1_1TriggerQueryHandler" ],
    [ "UrlHandler", "classalbert_1_1UrlHandler.html", "classalbert_1_1UrlHandler" ],
    [ "WeakDependency", "classalbert_1_1WeakDependency.html", "classalbert_1_1WeakDependency" ],
    [ "cacheLocation", "namespacealbert.html#a9815442f0654991511ecd0f0d7d7e959", null ],
    [ "configLocation", "namespacealbert.html#a9e4a5e745c6c8d4dc7dc0827caac1def", null ],
    [ "dataLocation", "namespacealbert.html#a7f6fbbcaf1a50138c135a5831eeb5c6a", null ],
    [ "extensionRegistry", "namespacealbert.html#ad686c346ceb5a0fa99659e5c3a627bb1", null ],
    [ "quit", "namespacealbert.html#ab3146bc3f5c4199dcf3c67c2ce399dd9", null ],
    [ "restart", "namespacealbert.html#a7c912d042d2e07024785b691c1121647", null ],
    [ "settings", "namespacealbert.html#a09085231379cd9843cd3064606bc0766", null ],
    [ "show", "namespacealbert.html#a40c3dac8ce8b95348a840eaa9051a4a7", null ],
    [ "showSettings", "namespacealbert.html#aa58d49c3ab5bd7282b0ee46a5e9db8fd", null ],
    [ "state", "namespacealbert.html#a1998f7413d7a26e994fc3a8ff17df336", null ]
];